[package]
name = "fabric-switchboard"
version.workspace = true
edition.workspace = true
license.workspace = true
[build-dependencies]
tauri-build = { version = "2", features = [] }
[dependencies]
switchboard-runtime = { path = "../crates/switchboard-runtime" }
switchboard-core = { path = "../crates/switchboard-core" }
tauri = { version = "2", features = [] }
serde_json.workspace = true
