// Offline receipts: shared source bytes, generated native assets, roles, and versions.
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
const read = (path) => readFileSync(path, 'utf8');
const json = (path) => JSON.parse(read(path));
const hash = (path) => createHash('sha256').update(readFileSync(path)).digest('hex');
const manifest = json('brand/passioncode/manifest.json');
assert.match(manifest.commit, /^[a-f0-9]{40}$/);
for (const file of manifest.files) assert.equal(hash(file.vendored), file.sha256, `${file.vendored}: canonical source drift`);
const native = json('brand/passioncode/native-icons.json');
for (const [file, digest] of Object.entries(native.sha256)) assert.equal(hash(file), digest, `${file}: generated icon drift`);
const tokens = read('brand/passioncode/tokens.css');
const adapter = read('src/tokens.css');
const styles = read('src/style.css');
const declared = new Set([...`${tokens}\n${adapter}`.matchAll(/(--[\w-]+)\s*:/g)].map((match) => match[1]));
for (const match of `${tokens}\n${adapter}\n${styles}`.matchAll(/var\((--[\w-]+)\)/g)) assert(declared.has(match[1]), `Undefined role: ${match[1]}`);
assert(!/#[\da-f]{3,8}\b/i.test(adapter + styles), 'Component layer must consume shared color roles');
const main = read('src/main.ts');
assert(!main.includes('prefers-color-scheme'), 'The requested default is fixed dark');
assert(main.includes("dataset.theme = 'dark'"));
assert(main.includes("import switchboardMark from '../brand/passioncode/switchboard-mark.svg'"));
assert(main.includes('mark.src = switchboardMark'));
const version = json('package.json').version;
assert.equal(json('package-lock.json').version, version);
assert.equal(json('package-lock.json').packages[''].version, version);
assert.equal(json('src-tauri/tauri.conf.json').version, version);
assert.equal(read('Cargo.toml').match(/\[workspace.package\]\nversion = "([^"]+)"/)[1], version);
for (const match of read('Cargo.lock').matchAll(/name = "(?:fabric-switchboard|switchboard-cli|switchboard-proxy|switchboard-runtime)"\nversion = "([^"]+)"/g)) assert.equal(match[1], version);
console.log(`PassionCode ${manifest.version}: 2 canonical sources, 3 native assets, CSS roles and version ${version} verified`);
