import { invoke, isTauri } from '@tauri-apps/api/core';
import type { Adapter } from './types';
import { readWithDeadline, READ_TIMEOUT } from './read-deadline';
export const reportFrontendReady = () => invoke('frontend_ready');

export const native = isTauri();
export const demo = !native && new URLSearchParams(location.search).get('demo') === '1';
export const nativeAdapter: Adapter = {
  snapshot: () => readWithDeadline(invoke('snapshot')),
  currentAccounts: () => readWithDeadline(invoke('current_accounts')),
  captureCurrent: (input) => invoke('capture_current', { ...input }),
  importClaudeSwap: (pool) => invoke('import_claude_swap', { pool }),
  activateNative: (id) => invoke('activate_native', { id }),
  setPolicy: (policy) => invoke('set_policy', { policy }),
  monitorStatus: () => readWithDeadline(invoke('monitor_status')),
  runtime: () => readWithDeadline(invoke('runtime_status')),
  add: (input) => invoke('add_account', { ...input }),
  update: (id, label, enabled) => invoke('update_account', { id, label, enabled }),
  remove: (id) => invoke('remove_account', { id }),
  select: ({ id, provider, pool }) => invoke('select_account', { id, provider, pool }),
  launch: (id, mode, workingDirectory) => invoke('launch_account', { id, mode, workingDirectory }),
  beginLogin: (input) => invoke('begin_login', { ...input }),
  loginStatus: (loginId) => readWithDeadline(invoke('login_status', { loginId })),
  finishLogin: (loginId) => invoke('finish_login', { loginId }),
  cancelLogin: (loginId) => invoke('cancel_login', { loginId }),
  probe: (id) => invoke('probe_usage', { id }),
  setProjectRule: (input) => invoke('set_project_rule', { ...input }),
  removeProjectRule: (path, provider) => invoke('remove_project_rule', { path, provider }),
  agentSetup: () => readWithDeadline(invoke('agent_setup')),
  backups: () => readWithDeadline(invoke('backups')),
  backupNow: () => invoke('backup_now'),
  restoreBackup: (file) => invoke('restore_backup', { file }),
  linkCli: () => invoke('link_cli'),
};

// Only exact, fixed backend vocabulary is surfaced. Unknown failures never print
// raw provider output, credentials, filesystem paths, or serialized error objects.
const safeErrors = new Set([
  READ_TIMEOUT,
  'Disable the existing Claude CLI rotation policy before enabling another pool.',
  'Claude account lock was lost after credential write. Sign in through Claude before retrying.',
  'Provider CLI not found. Install the official CLI and retry.',
  'Sign-in is not complete. Finish in Terminal, then try again.',
  'Managed mode requires a selected account in this pool.',
  'Usage unavailable for this credential type.',
  'Provider rejected the credential. Sign in again.',
  'Storage unavailable. Check native credential storage access and retry.',
  'Select another account in this pool, or disable this account, before removing it.',
  'This account is disabled. Enable it before continuing.',
  'Enter valid credential JSON for the selected provider.',
  'Enter a credential before adding the account.',
  'This credential type is not supported by this provider.',
  'Choose an existing project directory.',
  'Close the existing session before changing its home.',
  'Select another account before removing this one.',
  'Select this account before launching managed mode.',
  'Captured Codex login has no identity token. Sign in again or use managed mode.',
  'Account saved; isolated login cleanup needs attention.',
  'Finish or close sign-in in Terminal before cancelling.',
  'Usage is available for OAuth profiles only.',
  'Usage unavailable. Check sign-in or try again after the next scheduled check.',
  'Native activation requires a Claude OAuth profile.',
  'Capture or import this profile before native activation.',
  'Current CLI account changed. Refresh before switching.',
  'Keychain unavailable. Unlock it and allow access, then retry.',
  'Claude secure storage points at another profile. Use a shell with matching Claude settings.',
  'This Codex credential store cannot be imported. Use official sign-in to add a profile.',
  'This Codex keyring backend cannot be imported yet. Use official sign-in to add a profile.',
  'Current sign-in changed during capture. Try again.',
  'Claude Swap profiles changed during import. Try again.',
  'Capture this Claude profile again before native activation.',
  'Current Claude account changed. Refresh the account list, then retry.',
  'Current Claude credential is unavailable; activation was cancelled.',
  'Current Claude account changed during activation. Try again.',
  'Claude account lock was lost after credential write. Sign in through Claude before retrying.',
  'Claude activation failed; previous account restored.',
  'Claude activation failed and rollback needs attention. Sign in through Claude before retrying.',
  'Open Claude Code once before activating a profile.',
  'Claude is updating its account. Wait for login or refresh to finish, then retry.',
  // Safety-critical: the rollback could not confirm which Claude account is active. Shown verbatim.
  'Claude rollback lost its account lock. Check the current Claude sign-in before retrying.',
  'Claude account lock is unavailable. Check permissions of the Claude config directory.',
  'Choose an absolute project folder.',
  'Choose an existing project folder.',
  'Choose an expiry in the future.',
  'Project rule not found.',
  'This build has no bundled command-line tool.',
  '~/.local/bin/switchboard already points elsewhere. Remove it first.',
  '~/.local/bin/switchboard already exists and is not a link. Remove it first.',
  'Could not create ~/.local/bin.',
  'Keep switchboard.exe from the download folder, or add it to PATH.',
  'Finish an existing sign-in before starting another.',
  "This account's sign-in has ended. Sign in to it again.",
  'Sign-in not found. Start again.',
  'This backup was made with another key and cannot be opened on this machine.',
  'Choose a backup from the backup folder.',
  'Backup not found. Refresh the list and choose another.',
  'This file is not a Switchboard backup.',
  'This backup is damaged and cannot be restored.',
  'Backups are written by the desktop app or switchboard serve.',
  'Backups are restored by the desktop app or switchboard serve.',
  'The Documents folder is unavailable for backups.',
  'Backup storage unavailable. Check the backup folder and Keychain access.',
]);
const coreErrors: Record<string, string> = {
  'No current Claude sign-in found.': 'No current Claude sign-in found. Sign in with the official CLI, then capture again.',
  'No current Codex sign-in found.': 'No current Codex sign-in found. Sign in with the official CLI, then capture again.',
  'No Claude Swap profiles found.': 'No Claude Swap profiles found in the standard local location. Save a profile in Claude Swap, then retry.',
  'External sign-in unavailable or its files are unsafe.': 'The external profile could not be read safely. Check the CLI profile and storage permissions, then retry.',
  'Claude Swap account index is invalid.': 'The Claude Swap profile index could not be read. Check the source profiles, then retry.',
  'Invalid rotation policy': 'Check the policy bounds. Headroom must be less than the threshold; cooldown must be at most 604800 seconds and usage age from 1 to 86400 seconds.',
  'Claude credential write needs Keychain access.': 'Claude activation needs Keychain access. Unlock Keychain and allow access, then retry.',
  'Claude credential rollback needs Keychain access.': 'Credential recovery needs Keychain access. Unlock Keychain and sign in through Claude before retrying.',
  'Storage unavailable. Check Keychain access and retry.': 'Storage unavailable. Check native credential storage access and retry.',
  'Codex does not support setup tokens': 'Choose an API key, imported OAuth JSON, or official sign-in for Codex.',
  'Credential format is invalid': 'Check the credential format and enter it again.',
  'Credential input is empty or too large': 'Enter a credential within the supported size limit.',
  'OAuth JSON is invalid': 'Enter valid credential JSON for the selected provider.',
  'Unsupported OAuth JSON schema': 'This OAuth JSON format is not supported. Use the official sign-in flow instead.',
  'OAuth access token is missing': 'The imported JSON has no access token. Sign in again or import a complete credential.',
  'OAuth field type is invalid': 'The OAuth JSON contains an invalid field. Use a complete provider credential export.',
  'OAuth expiration is invalid': 'The OAuth expiration is invalid. Sign in again or import a complete credential.',
  'Label or pool is invalid': 'Enter a label and a pool using lowercase letters, numbers, hyphens, or underscores.',
  'Label, pool or identity is invalid': 'Enter a label and a pool using lowercase letters, numbers, hyphens, or underscores.',
  'Account identity is ambiguous in this pool': 'More than one account in this pool has this identity. Remove the duplicate, then retry.',
  'Sign-in cleanup needs Keychain access.': 'Sign-in cleanup needs Keychain access. Unlock Keychain and allow access, then cancel again.',
  'Terminal could not open.': 'Terminal could not open. Check that Terminal is available, then retry.',
  'Rotation time precedes the last switch': 'The system clock is earlier than the last automatic switch. Check the date and time settings, then retry.',
  'Label is invalid': 'Enter a nonempty account label within the supported length limit.',
  'Account limit reached': 'The account limit has been reached. Remove an unused account before adding another.',
  'Account credential already exists in this pool': 'This credential already exists in this provider and pool. Use the existing account.',
  'Select another account or disable this account before removing it': 'Select another account in this pool, or disable this account, before removing it.',
  'Account is disabled': 'This account is disabled. Enable it before continuing.',
  'Credential expired; reauthenticate this account': 'This credential has expired. Sign in to this account again.',
  'Credential storage unavailable; reauthenticate this account': 'The stored credential is unavailable. Check native credential storage access or sign in again.',
  'No account selected for this provider and pool': 'Select an account in this provider and pool before launching managed mode.',
  'Account is unavailable in this provider and pool': 'This account is unavailable in the chosen provider and pool. Refresh the account list.',
  'Selected account unavailable': 'The selected account is unavailable. Refresh and select an enabled account.',
  'Account not found': 'This account no longer exists. Refresh the account list.',
  'Invalid usage observation': 'The provider returned an invalid usage observation. The last observation is unchanged.',
  'Usage observation is older than the stored observation': 'The provider returned an older observation. The last observation is unchanged.',
  'Another Switchboard instance owns this account storage': 'Another Switchboard window owns the account storage. Close that instance, then retry.',
  'Account metadata is corrupt; restore a known-good backup': 'Account metadata could not be read. Restore a known-good backup before continuing.',
  'Unsupported account metadata version': 'This account metadata version is not supported. Open it with a compatible Switchboard version.',
  'Account metadata could not be saved': 'Account metadata could not be saved. Check storage access and retry.',
  'Storage failure; credential cleanup requires recovery': 'The account could not be saved and credential cleanup needs recovery. Check storage before retrying.',
  'Native vault is not implemented on this platform': 'Native credential storage is not available on this platform. Use a supported native build.',
  'Secure metadata storage is not implemented on this platform': 'Secure account storage is not available on this platform. Use a supported native build.',
};
for (const error of ['Vault unavailable', 'Credential unavailable', 'Native credential storage unavailable', 'Credential storage unavailable', 'Private account storage unavailable', 'Account store unavailable']) coreErrors[error] = 'Storage unavailable. Check native credential storage access and retry.';
for (const error of ['Unsafe account storage file', 'Unsafe account storage directory', 'Unsafe account metadata file', 'Invalid account metadata', 'Invalid route metadata', 'Invalid event metadata', 'Invalid metadata bounds', 'Invalid project rule metadata', 'Account metadata exceeds size limit']) coreErrors[error] = 'Account storage failed validation. Restore a known-good backup or check the app’s storage permissions before retrying.';
for (const error of ['External profile format is invalid.', 'External credential format is invalid.', 'Claude account identity is missing.', 'Codex config is invalid.', 'Claude credential and config identities differ.', 'Claude profile identity is missing.', 'Stored Claude identity differs from its native profile.', 'Claude native credential is missing.', 'Claude native credential is invalid.']) coreErrors[error] = 'The local CLI profile is incomplete or inconsistent. Complete official sign-in, then capture the account again.';
for (const error of ['Claude account lock was lost.', 'Claude account lock heartbeat failed.']) coreErrors[error] = 'The Claude account lock could not be kept. Wait for other account updates to finish, then refresh and retry.';
export function safeError(error: unknown): string {
  const candidate = typeof error === 'string' ? error : error instanceof Error ? error.message : '';
  return safeErrors.has(candidate) ? candidate : Object.hasOwn(coreErrors, candidate) ? coreErrors[candidate] : 'The operation could not be completed. Check your input and native credential storage access, then retry.';
}
